UKHomeOffice/asl-search

- lib/router/search.js
- lib/search.js
Defines a list of available search indexes and throws 404 errors if undefined index is hit.
Throws 400 if no search term is provided.
> Route based on search index and handle 40x errors

- lib/indexers/profiles.js
- lib/indexers/projects.js
- lib/search.js
These remove the need to smoosh data together into a single string and allow for weighting of query matching to particular fields.
> Use multi field searches

- lib/router/search.js
- lib/search.js
Respects the offset and limit parameters provided by the client.
Doesn't do anything with sorting yet.
> Add pagination to search results

- bin/indexer
- lib/indexers/projects.js
- lib/search.js
Allows defining a project search as `content: <term>` and searching the complete text of the project for matches.
> Full project content search

- lib/indexers/establishments.js
- lib/indexers/profiles.js
- lib/indexers/projects.js
- lib/search.js
If a licence number is entered then it should match the record exactly rather than fuzzy matching against all similar licence numbers.
Note: this PR branches from #17
> Support exact matching for licence numbers

- lib/indexers/establishments.js
- lib/indexers/profiles.js
- lib/indexers/projects.js
- lib/search.js
Defines a default sort order for each search type if no search term is defined (if a search term is defined then default to best match).
Defines keyword properties on each index to facilitate keyword sorting and fuzzy text matching where appropriate.
> Enable sorting of results

- lib/indexers/projects.js
These don't show up in traditional project search, so shouldn't be indexed here.
> Don't index unsubmitted drafts

- lib/indexers/projects.js
Add licence number to the allowed sortable fields
> Allow sorting by licence-number

- lib/indexers/establishments.js
- lib/indexers/profiles.js
- lib/indexers/projects.js
- lib/router/indexer.js
- lib/router/search.js
- lib/search.js
- package.json
Also add lint to `npm test` call to protect against similar issues in future.
> Add missing `get` requires

- bin/stats
To provide better visibility of performance and data in AWS instances.
> Add stats script

- lib/indexers/projects.js
- lib/search.js
Will atempt to restore this in some form, but remove it for now so that prod can be successfully indexed and searched based on core fields.
> Remove full content index and search from projects

- lib/indexers/projects.js
This needs to be in the index to display correctly in the result table.
> Add legacy stub flag to search index

- lib/indexers/projects/extract-species.js
- lib/indexers/projects/index.js
- package.json
Creates an aggregated list of project species and includes them on project index
> Index project species

- lib/router/search.js
This is to be able to easily extract aggregated search data from kibana.
> Add logging of search index/term

- lib/indexers/profiles/index.js
- lib/search/profiles.js
- package-lock.json
- package.json
* update indexer and search to use pilLicenceNumber from profile
> Feature - move pil licence number to profile

- lib/indexers/establishments.js
- lib/search/establishments.js
- package-lock.json
- package.json
~waiting on https://github.com/UKHomeOffice/asl-schema/pull/384~
> Add establishment.keywords to search index

- lib/api.js
- lib/router/indexer.js
- lib/router/search.js
- package-lock.json
- package.json
Makes a call to the elasticsearch API to ensure that it is available when `/healthcheck` is hit.
> Add custom healthcheck function

- lib/search/establishment-scoped/places.js
- lib/search/global/establishments.js
- lib/search/global/profiles.js
- lib/search/global/projects.js
- lib/search/helpers/sort-params.js
Use the "sortable" columns as a default sort order, in the order they are specified.
> Sort by multiple columns by default

- bin/search
- lib/indexers/projects/index.js
- lib/search/global/projects.js
- lib/search/global/search.js
This allows us to query all projects for their species, and get data about all the species used across all projects.
> Add species filtering/aggregation to project search

- lib/api.js
The healthcheck endpoint is failing sporadically on dev. Help to find out why.
> Log errors on healthcheck failures

- lib/indexers/places/index.js
If a place removal task is approved the place should be immediately removed from the search index so it no longer shows in establishment SoPs.
> Remove deleted places from the index

- lib/indexers/profiles/index.js
- lib/search/global/profiles.js
- lib/search/global/search.js
It means you have to type at least 4 chars to get a partial match, but the results are generally less noisy than using 3 letter ngrams which return a lot more results.
Basically, it functions more like a SQL style wildcard search: `%foob%`
> Use 4 letter ngrams for partial matching of full name

- lib/search/global/projects.js
- lib/search/global/search.js
* Added all-inactive filter which contains expired revoked and transferred
> Feature - group inactive project statuses

- lib/search/global/router.js
- lib/search/global/search.js
* Only combine inactive statuses if index is project
> Bugfix - dont combine inactive statuses for all the things

- lib/indexers/projects/index.js
* Added end date to project indexer
> Feature - end date for projects

- lib/search/establishment-scoped/places.js
* Added area to filters aggregates - this can be used for autocomplete
> Feature - places autocomplete

- lib/indexers/index.js
- lib/indexers/places/index.js
If a request is received to re-index an establishment then also re-index associated places.
> Re-index places on PEL change

- lib/indexers/projects-content/extract-content.js
- lib/indexers/projects-content/index.js
- lib/search/global/projects-content.js
- lib/search/global/router.js
* Added species to indexer
* Updated content extractor to include content fields for just nts and granted
* Added filters for ra, includes continuation and purposes
> Feature - project content search filters

- lib/indexers/establishments/index.js
- lib/indexers/profiles/index.js
- lib/indexers/projects/index.js
- package-lock.json
- package.json
New suspendedDate column needs to be indexed for displaying licence status in the search result lists.
> Feature: suspend licences

- lib/indexers/enforcements/index.js
- lib/indexers/index.js
- lib/search/global/enforcements.js
- lib/search/global/search.js
- package-lock.json
- package.json
* Added enforcements indexer
* Added enforcements search router
> Feature - Enforcements indexer

- lib/indexers/enforcements/index.js
- lib/search/global/enforcements.js
Adding to previous PR
* Added establishments keywords
* Added licence numbers for each enforcement type
> Feature - Enforcement

- lib/search/global/enforcements.js
* this has changed to subjects.profile.firstName etc
> Bugfix - enforcement profile

- package-lock.json
- package.json
https://github.com/elastic/elasticsearch-js/issues/1519
> Pin elastic search at 7.13.0 
