UKHomeOffice/asl-search

lib/indexers/profiles.js
New profiles in prod don't have any title property so indexing them will result in a lot of "undefined"
=> Don't index titles

bin/indexer, lib/indexers/index.js
This is cleaner than requiring the files individually and then consolidating into an object.
=> Use an indexers index file to consolidate requires

bin/indexer, bin/search, config.js, lib/indexers/establishments.js, lib/indexers/projects.js, lib/router/search.js, lib/search.js
Includes all the fields which the search pages expect to receive on search results.
We may want to optimise this in future because it stores some redundant data, but now it allows direct proxying of requests through the API to the search service.
=> Return results in expected format

bin/indexer
Seeds running on dev mean the ids for all dev data are periodically reset. This means that the old indexes need to be deleted when running on dev.
Add a flag that deletes the old index before creating a new one so that old dev records are purged from the index.
=> Add `--reset` flag to delete old indexes

lib/indexers/projects.js, lib/router/search.js, lib/search.js
The scope of this expanded a little. It now does:
* Add support for status filters
* Return all results if no search term
* Reduce scope of project search to limited fields (leaves full content index in place though)
=> Add status filters and total counts

lib/search.js
When the "All" filter is clicked the request has a status filter of `['']`. Don't apply an empty string to the query in that case.
=> Check status filter has a value before applying it

lib/search.js
Otherwise the status filters on an empty search return zero results as there are no "should" clauses to match.
=> Only set minimum_should_match if there is a search term

bin/indexer, lib/api.js, lib/indexers/establishments.js, lib/indexers/profiles.js, lib/indexers/projects.js, lib/router/indexer.js
Can hit `/establishments/:id` `/projects/:id` or `/profiles/:id` to refresh the index for a particular record without needing to rebuild the entire index.
The eventual use-case for this will be a workflow hook that refreshes the index on those entities whenever a task resolves that would update the data.
=> Add endpoint to re-index a specific record

lib/router/search.js
Instead of creating a new client for every request allow a single client to be used for all requests
=> Re-use elastic-search client

lib/indexers/profiles.js, lib/router/indexer.js, package.json
Establishment ids are not UUIDs so can't be validated as such
Also clean up some things that go t lost in earlier PRs:
* logging counts consistently in indexer
* restore npm script for indexer so that conductor works properly
=> Don't validate UUID

lib/indexers/projects.js, lib/search.js
If a user enters a search term with multiple words then run a separate search for each word and require that all words match in a result.
This means that adding additional search terms will make a search more specific rather than less specific, which aligns better with user expectations.
=> Split search term into words and combine with AND

lib/indexers/projects.js, lib/router/search.js, lib/search.js
Rather than hard-coding the list, use an aggregator query to get the complete set of statuses present in the data-set.
=> Return dynamic list of statuses

lib/indexers/projects.js
The default is 1000, which causes the indexxer to fail on preprod.
=> Set maximum fields to 2000 on projects index

lib/errors/elastic.js, lib/errors/index.js, lib/router/search.js
We were losing a lot of metadata from the elastic error by flattening it to single string. Instead add the entire error data to the error object so it can be logged.
=> Improve error logging for elastic errors

bin/search, lib/indexers/projects.js, lib/router/search.js, lib/search.js, package.json
Allows adding custom extra fields to index as well as rte content, but otherwise ignores all non-RTE data.
Also includes matching field data in full content search response.
=> Limit project index to only rich text inputs

lib/indexers/profiles.js, lib/router/search.js
This allows the complete set of profile data from prod to be included in a search. It can result in an increase increase in resource usage and impaired performance, but testing locally on a ~30,000 record dataset with a less powerful elastic instance than prod works fine - presumably because the index data is still small (~5mb total size).
Over 10,000 results the results counter loses accuracy and only returns a count of `gte` 10000, so if that happens then reset the result counter to assume we're getting all the results, because in 100% of our use cases that's what is happening.
=> Increase max results window setting for profiles index

lib/search.js
This enable searching for a partial establishment name - for example `croy` will match `University of Croydon`.
This better matches user behaviour in prod where ASRU users input the first few characters of an establishment and hit enter.
=> Add partial substring matching to establishment search

lib/search.js
Can search for the name of a SPoC or Inspector in the establishment search and get a list of their establishments. Boost the establishment name so name matches appear first if they exist.
=> Allow matching establishments by ASRU assignment

lib/indexers/projects.js
This needs to be present in order to support sorting by that field.
=> Add value property on project status

lib/indexers/establishments.js, lib/indexers/profiles.js, lib/indexers/projects/index.js, lib/search.js
Licence number matches are strictly case sensitive, so index as uppercase always and search as uppercase.
=> Normalise licence numbers to uppercase

lib/search.js
This ensures consistent results irrespective of the casing used in the input.
=> Set non-licence number search terms to lower case

lib/search.js
Currently a close match on the surname comes ahead of an exact match on the first name, which is unexpected. Boost the first name so that an exact match will come in front of fuzzy surname matches.
=> Add additional weight to first name matches

lib/search/establishments.js, lib/search/projects.js
The search function was returning early if there is no search term, which was not applying status filters. Move the status filter to before the early return.
=> Apply status filters to all searches

lib/search/establishments.js, lib/search/profiles.js, lib/search/projects.js
The code to handle a defined search term was removing the earlier status filter. Instead extend the query with additional parameters.
=> Don't reset query when there is a search term

lib/indexers/profiles/index.js
The whitespace tokeniser preserves double-barrelled names so they only match if searched on the complete name with hyphen and not either part.
Instead use the standard tokeniser so that either barrel will match, as will omitting the hyphen.
=> Use standard tokeniser for profile names

lib/indexers/profiles/index.js
The field was not included in the initial `select` so was not being indexed and search by PIL licence number was returning no results.
=> Add PIL licence number to indexed fields in profile search

lib/search/establishments.js, lib/search/profiles.js, lib/search/projects.js, lib/search/sort-params.js
This throws an error if an undefined column is used to apply a sort. Prevent that by ignoring sort parameters if the column defined is not sortable.
=> Filter sortable columns for result sorting

lib/elasticsearch/index.js
AWS signed credentials have a TTL and at the moment if that expires then the service stops working until it is restarted.
Use the wrapper function in the AWS credentials library that solves this precise problem - https://github.com/mergermarket/acuris-aws-es-connection/tree/v1.1.0#how-does-it-work
=> Handle expired AWS credentials

lib/search/sort-params.js
This means that when hitting the search pages without a term entered the results will always be ordered in the same way (by name/title).
Specifically it means the visual regressions won't throw false positives because the result ordering is random.
=> Apply default sort order to empty search

lib/elasticsearch/index.js, package-lock.json, package.json
The `awsCredsifyAll` function did not do what it claimed, and has disappeared in the latest version. Use that in the futile hope that it actually works.
=> Update elastic client

lib/search/establishment-scoped/places.js
It's not possible for a place to exist in more than one site, so it only makes sense for that filter to work as an OR.
=> Convert site filter to an OR

lib/indexers/profiles/index.js, lib/search/global/profiles.js
The previous approach was incorrect because it didn't exclude them from the overall count.
Instead simply don't index ASRU users in the first place.
=> Remove ASRU users from index

lib/search/global/search.js
This only gives the top 10 by default, which is fairly useless for our purposes.
=> Add size parameter to species aggregation

bin/search
* `JSON.stringify` results so that they can be piped into `jq` for processing
* Only output aggregated species if requested because they add a lot of noise and get in the way of search results
=> Improve CLI search result output

lib/indexers/places/index.js
These are used in the schedule of premises to render the exclamation indicators where a row has restrictions.
=> Include restrictions in index of places

lib/indexers/projects-content/extract-content.js
There are some old projects on preprod which end up having null entries in the protocols array.
Don't try to index those.
=> Handle null protocols

lib/indexers/projects-content/extract-content.js, lib/indexers/projects-content/index.js
Indexing by id results in a field per protocol, and elasticsearch has a 1000 field limit.
=> Index protocols by array index and not id

lib/api.js
This is creating a large number of false positives in dev, resulting in high levels of instability and corresponding failing tests.
=> Remove call to es in healthcheck

lib/search/helpers/sort-params.js
Doing relevancy scoring on small indexes doesn't work reliably by default across multiple shards. This means search results can be returned in an unexpected order when sorting by score (default sort).
The workaround for this is to set the search_type property so all shards are queried when assembling statisitics for relevancy scores. Since this has a perf impact but is only relevant when sorting by score set the param only if no specific sort column is defined.
=> Set search type when no sort order is defined

lib/indexers/places/index.js
Removed place roles should now be reflected in the search results immediately.
=> Place query was ignoring deleted role joins and including them

lib/indexers/projects/index.js
This meant that they were not being returned in the CSV export of the project search.
=> Issue date and revocation date were missing from the index

lib/indexers/projects-content/index.js
These are now displayed in search results.
There's probably a case for consolidating to a single project index now, but I'll save that for a separate PR.
=> Add dates to project content index

lib/indexers/projects-content/index.js
The whitespace tokenizer treats punctuation as significant so words don't match if they precede a full stop or comma or similar.
Using the standard tokenizer means that punctuation is ignored in search matches.
=> Use standard tokenizer for project content search

lib/search/global/projects-content.js
This allow search terms that appear in the project title to be specifically highlighted in search results.
=> Include title matches in project content result highlights

lib/search/global/projects-content.js
This means that projects which match the search term in their title will rank higher than projects where the search term appears in the main body of the application.
=> Add a boost to title matches in full-content project search

lib/search/global/projects-content.js
There are some issues with CSV downloads of large result sets failing on prod. Also an issue with results with only a single term in the search query in the title being returned.
* add an extended timeout to improve chances of doing CSV export
* remove highlighting if large number of rows requested (i.e. is a CSV download)
* add `AND` operator to title search so all terms in search query must match
=> Assorted full content search improvements

lib/indexers/establishments/index.js, lib/indexers/places/index.js, lib/indexers/profiles/index.js, lib/indexers/projects-content/index.js, lib/indexers/projects/index.js, lib/indexers/utils/delete-index.js
There is no way to switch off snapshot collection, but rebuilding the indexes will occasionally fail because it can't be deleted while a snapshot is in progress.
Instead if that error is thrown in response to a deletion then wait 30 seconds and try again.
=> Retry index deletion if it fails with a snapshot in progress

lib/search/global/router.js
This makes it a little easier on the client to debug issues with ordering of search results.
=> Include score in response sets

lib/search/global/projects-content.js
Currently the results of the default view of advanced project search are random. This causes a difference in the visual regression every time it runs.
Set the default sort order when no search term is provided to title for consistency with regular project search.
=> Sort advanced project search by title if no search term provided

lib/indexers/profiles/index.js
This was causing spaces between names to be included in search matches, and consequently malformed markdown to be generated in highlight matches - e.g. `**jean claude van **damme`
Removing the whitespace from the characters allowed in ngrams prevents this but does not seem to obviously affect the quality of matches.
=> Remove whitespace from ngram tokeniser

lib/indexers/enforcements/index.js
Not having the id breaks the "View case" links in the enforcement list, as well as meaning that incoming requests to update an index always create a new search entry rather than updating existing rows.
=> Include id in enforcements index
